local Car = require "scripts.car"
local Controls = require "scripts.controls"
local Sensors = require "scripts.sensors"
local TrafficManager = require "scripts.traffic_manager"


local function draw_polygon(polygon)

	for i = 1, #polygon do

		local next_i =
		(i % #polygon) + 1

		local a = polygon[i]
		local b = polygon[next_i]

		msg.post(
		"@render:",
		"draw_line",
		{
			start_point =
			vmath.vector3(
			a.x,
			a.y,
			0
		),

		end_point =
		vmath.vector3(
		b.x,
		b.y,
		0
	),

	color =
	vmath.vector4(1, 0, 0, 1)
}
)
end
end

function init(self)
	msg.post(".", "acquire_input_focus")

	print("CAR SCRIPT INITIALIZED")
	
	local position = go.get_position()
	local CONTROL_MODE = "KEYS"

	self.x = position.x
	self.y = position.y
	self.speed = 0
	self.angle = 0
	
	self.car = Car.new(
	300,
	100,
	30,
	50,
	CONTROL_MODE
	) 

	self.sensor = Sensors.new(self.car)

	self.debug = true
	self.car.polygon = Car.create_polygon(self.car)

	print("CAR INITIALIZED")
	print("CAR POLYGON CREATED")

	print(
	"SENSOR CREATED"
)

print(
"RAY COUNT:",
self.sensor.ray_count
)

print(
"RAY LENGTH:",
self.sensor.ray_length
)

print(
"RAY SPREAD:",
self.sensor.ray_spread
)
	
end

function final(self)
end

function update(self, dt)
	if not self.car.damaged then
		
		Car.move(self.car)
		self.car.polygon = Car.create_polygon(self.car) 

		--print("ROAD BORDERS:",self.road_borders)
		Sensors.cast_rays(self.sensor)
		
		print("TRAFFIC COUNT:",	#TrafficManager.get_all())
		Sensors.update(
		self.sensor,
		self.road_borders,
		TrafficManager.get_all()
		)
		
		if self.debug then
			Sensors.draw(self.sensor)
		end

		for i, reading in ipairs(self.sensor.readings) do

			if reading then

				print(
				"SENSOR",
				i,
				"DETECTED",
				"X:",
				reading.x,
				"Y:",
				reading.y,
				"OFFSET:",
				reading.offset
			)

		else

			print(
			"SENSOR",
			i,
			"NO DETECTION"
		)

	end

end

		for i, ray in ipairs(self.sensor.rays) do

			print(
			"RAY",
			i,
			"START:",
			ray[1].x,
			ray[1].y,
			"END:",
			ray[2].x,
			ray[2].y
			)

		end
		
		print("DAMAGE", self.car.damaged)
		if self.road_borders then
			self.car.damaged = 
			Car.assess_damage(
			self.car,
			self.road_borders,
			{}
			)
			print("DAMAGE",self.car.damaged)
		end
	end 

	if self.debug then
		draw_polygon(self.car.polygon)
	end

	--Sensors.draw()	
	go.set_position(
	vmath.vector3(
	self.car.x,
	self.car.y,
	0
		)
	)

	go.set_rotation(
	vmath.quat_rotation_z(
	-self.car.angle
		)
	)    

end


function on_message(self, message_id, message, sender)

	if message_id == hash("set_road") then

		self.road_borders = {
			{
				vmath.vector3(
				message.left,
				-1000,
				0
			),

			vmath.vector3(
			message.left,
			1000,
			0
		)
	},

	{
		vmath.vector3(
		message.right,
		-1000,
		0
	),

	vmath.vector3(
	message.right,
	1000,
	0
)
}
}

print("ROAD BORDERS RECEIVED")


end


	
end

function on_input(self, action_id, action)
	
		

		if action.pressed then
			
			Controls.apply_input(
			self.car.controls,
			action_id,
			action
			)

		end

		if action.released then
			

			Controls.release_input(
			self.car.controls,
			action_id
			)

			
		end 

		
	
end


