local Car = require "scripts.car"
local Controls = require "scripts.controls"


local function draw_polygon(polygon)

	for i = 1, #polygon do

		local next_i =
		(i % #polygon) + 1

		local a = polygon[i]
		local b = polygon[next_i]

		msg.post(
		"@render:",
		"draw_line",
		{
			start_point =
			vmath.vector3(
			a.x,
			a.y,
			0
		),

		end_point =
		vmath.vector3(
		b.x,
		b.y,
		0
	),

	color =
	vmath.vector4(1, 0, 0, 1)
}
)
end
end

function init(self)
	msg.post(".", "acquire_input_focus")

	print("CAR SCRIPT INITIALIZED")
	
	local position = go.get_position()
	local CONTROL_MODE = "KEYS"

	self.x = position.x
	self.y = position.y
	self.speed = 0
	self.angle = 0

	self.car = Car.new(
	300,
	100,
	30,
	50,
	CONTROL_MODE
	)

	self.car.polygon = Car.create_polygon(self.car)

	print("CAR INITIALIZED")
	print("CAR POLYGON CREATED")
	
-- 	for i, point in ipairs(self.car.polygon) do
-- 
-- 		print(
-- 		"CAR POINT",
-- 		i,
-- 		point.x,
-- 		point.y
-- 	)
-- 
-- 	end 



end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	Car.move(self.car)
	self.car.polygon = Car.create_polygon(self.car) 
	print("CAR:", self.car.x, self.car.y)
	print(
	"P1:",
	self.car.polygon[1].x,
	self.car.polygon[1].y
	)

	if self.debug then
		draw_polygon(self.car.polygon)
	end

	-- print(
	-- "P2:",
	-- self.car.polygon[2].x,
	-- self.car.polygon[2].y
	-- )
	
	go.set_position(
	vmath.vector3(
	self.car.x,
	self.car.y,
	0
		)
	)

	go.set_rotation(
	vmath.quat_rotation_z(
	-self.car.angle
		)
	)    

	print(
	"CAR POSITION:",
	self.car.x,
	self.car.y
	)

	print(
	"mode:",
	self.car.controls.type,
	"forward:",
	self.car.controls.forward,
	"left:",
	self.car.controls.left,
	"right:",
	self.car.controls.right,
	"reverse:",
	self.car.controls.reverse
)


end

function late_update(self, dt)
end

function fixed_update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
	
		

		if action.pressed then
			print("Pressed:", action_id)

			Controls.apply_input(
			self.car.controls,
			action_id,
			action
			)

			print( "FORWARD:", 	self.car.controls.forward)

			print(	"LEFT:",	self.car.controls.left)

			print( "RIGHT:", self.car.controls.right)

			print("REVERSE:", self.car.controls.reverse)
		end

		if action.released then
			

			Controls.release_input(
			self.car.controls,
			action_id
			)

			print(
			"RELEASED - FORWARD:",
			self.car.controls.forward
			)
		end 

		
	
end

function on_reload(self)
end
