local Controls = require "scripts.controls"



function init(self)
	print("Self-driving car simulation started")
	msg.post(".", "acquire_input_focus")
	self.controls = Controls.new("KEYS")
end

function final(self)

end

function update(self, dt)
end

function late_update(self, dt)

end

function fixed_update(self, dt)
	
end

function on_message(self, message_id, message, sender)

end

function on_input(self, action_id, action)
	if action.released then
		Controls.release_input(
		self.controls,
		action_id
	)
	elseif action.pressed then
		Controls.apply_input(
		self.controls,
		action_id,
		action
	)
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
