--local Controls = require "scripts.controls"
local Road = require "scripts.road"

--test of line intersection


-- local function test_polygon_intersection()
-- 
-- 	local polygon_a = {
-- 		vmath.vector3(0, 0, 0),
-- 		vmath.vector3(100, 0, 0),
-- 		vmath.vector3(100, 100, 0),
-- 		vmath.vector3(0, 100, 0)
-- 	}
-- 
-- 	local polygon_b = {
-- 		vmath.vector3(50, 50, 0),
-- 		vmath.vector3(150, 50, 0),
-- 		vmath.vector3(150, 150, 0),
-- 		vmath.vector3(50, 150, 0)
-- 	}
-- 
-- 	local polygon_c = {
-- 		vmath.vector3(200, 200, 0),
-- 		vmath.vector3(300, 200, 0),
-- 		vmath.vector3(300, 300, 0),
-- 		vmath.vector3(200, 300, 0)
-- 	}
-- 
-- 	local result = Geometry.polys_intersect(polygon_a, polygon_c)
-- 	print("result from intersection", result)
-- 
-- 	if result then
-- 		print("POLY INTERSECTION:")
-- 	else
-- 		print("NO POLY INTERSECTION")
-- 	end
-- end



function init(self)


	print("Self-driving car simulation started")

		
	-- test_polygon_intersection()

	--------------------------------------------------
	-- Create road
	--------------------------------------------------
	self.road =
		Road.new(
			480,
			540,
			3
		)



	--------------------------------------------------
	-- Send road borders to player car
	--------------------------------------------------
	msg.post(
		"/car",
		"set_road",
		{
			left = self.road.left,
			right = self.road.right
		}
	)

	print("ROAD SENT TO CAR")

	--------------------------------------------------
	-- Spawn traffic
	--------------------------------------------------
	
	local x = Road.get_lane_center(self.road,0)
	print("LOCAL X", x)
	self.traffic_id = factory.create("/traffic#factory", vmath.vector3(x,300,0))
	print("TRAFFIC SPAWNED:", self.traffic_id)
	

	
end






