local Controls = require "scripts.controls"
local Road = require "scripts.road"
local Geometry = require "scripts.geometry" 

--test of line intersection


-- local function test_polygon_intersection()
-- 
-- 	local polygon_a = {
-- 		vmath.vector3(0, 0, 0),
-- 		vmath.vector3(100, 0, 0),
-- 		vmath.vector3(100, 100, 0),
-- 		vmath.vector3(0, 100, 0)
-- 	}
-- 
-- 	local polygon_b = {
-- 		vmath.vector3(50, 50, 0),
-- 		vmath.vector3(150, 50, 0),
-- 		vmath.vector3(150, 150, 0),
-- 		vmath.vector3(50, 150, 0)
-- 	}
-- 
-- 	local polygon_c = {
-- 		vmath.vector3(200, 200, 0),
-- 		vmath.vector3(300, 200, 0),
-- 		vmath.vector3(300, 300, 0),
-- 		vmath.vector3(200, 300, 0)
-- 	}
-- 
-- 	local result = Geometry.polys_intersect(polygon_a, polygon_c)
-- 	print("result from intersection", result)
-- 
-- 	if result then
-- 		print("POLY INTERSECTION:")
-- 	else
-- 		print("NO POLY INTERSECTION")
-- 	end
-- end



function init(self)
	print("Self-driving car simulation started")

	msg.post(".", "acquire_input_focus")

	self.controls = Controls.new("KEYS")
	-- test_polygon_intersection()


	self.road =
		Road.new(
			480,
			540,
			3
		)

	msg.post(
		"/car",
		"set_road",
		{
			left = self.road.left,
			right = self.road.right
		}
	)

	local x = Road.get_lane_center(self.road,0)
	print("LOCAL X", x)
	self.traffic_id = factory.create("/traffic#factory", vmath.vector3(x,300,0))
	print("TRAFFIC SPAWNED:", self.traffic_id)
	
	

	
end


function on_message(self, message_id, message, sender)

end

function on_input(self, action_id, action)
	if action.released then
		Controls.release_input(
		self.controls,
		action_id
	)
	elseif action.pressed then
		Controls.apply_input(
		self.controls,
		action_id,
		action
	)
	end
end

function on_reload(self)
	
end
