local Road = require "scripts.road"

local function get_lane_x(road, lane)
	local lane_width = road.width / road.lane_count

	return road.left + lane_width * lane
end

function init(self)
	print("=== ROAD SCRIPT STARTED ===")

	self.road = Road.new(
		480,
		540,
		3
	)

	print("Road X:", self.road.x)
	print("Road width:", self.road.width)
	print("Lane count:", self.road.lane_count)
	print("Left:", self.road.left)
	print("Right:", self.road.right)

	local lane_width =
	self.road.width / self.road.lane_count

	print("Lane width:", lane_width)

	for lane = 1, self.road.lane_count - 1 do

		local x = get_lane_x(
		self.road,
		lane
	)

	print(
	"Divider",
	lane,
	"X:",
	x
)
end
	
end



function final(self)
	
end

function update(self, dt)
	
end

function late_update(self, dt)
	
end

function fixed_update(self, dt)
	
end

function on_message(self, message_id, message, sender)
	
end

function on_input(self, action_id, action)
	
end

function on_reload(self)
	
end
