local Road = require "scripts.road"
local Car = require "scripts.car"

function init(self)
	math.randomseed(os.time())

	self.road = Road.new(480, 540, 3) 

	print("SIM ROAD")
	print("X:", self.road.x)
	print("WIDTH:", self.road.width)
	print("LANES:", self.road.lane_count)
	print("LEFT:", self.road.left)
	print("RIGHT:", self.road.right)

	self.player = Car.new(Road.get_lane_center(	self.road, 1),
		300,
		30,
		50,
		"KEYS"
	)

	print("=== PLAYER CREATED ===") 

	print(
	"PLAYER:",
	self.player.x,
	self.player.y
)

print(
"PLAYER CONTROL:",
self.player.controls.type
)

print(
"PLAYER SENSOR:",
self.player.sensor ~= nil
)

print(
"PLAYER BRAIN:",
self.player.brain ~= nil
)
---- ======== Test for player sensing traffic =======
for i, reading in ipairs(
self.player.sensor.readings
) do

if reading then

	print(
	"PLAYER SENSOR",
	i,
	"DETECTED",
	reading.x,
	reading.y,
	"OFFSET",
	reading.offset
)

else

print(
"PLAYER SENSOR",
i,
"NO DETECTION"
)

end

end
--======= End of sensing traffic test =====
	self.traffic = {
		Car.new(Road.get_lane_center(self.road, 1),
			450,
			30,
			50,
			"DUMMY",
			2
		)
	}
	print("PLAYER DAMAGE:", self.player.damaged)
	print("=== ============= ===")
	print("=== TRAFFIC CREATED ===")

	print(
	"TRAFFIC COUNT:",
	#self.traffic
)

print(
"TRAFFIC POSITION:",
self.traffic[1].x,
self.traffic[1].y
)

print(
"TRAFFIC CONTROL:",
self.traffic[1].controls.type
)

print(
"TRAFFIC SPEED:",
self.traffic[1].speed
)

print(
"TRAFFIC POLYGON:",
self.traffic[1].polygon
)

	print("=== SIMULATION INITIALIZED ===")
end


function update(self, dt)

	if self.traffic[1] then
		print(
		"TRAFFIC BEFORE:",
		self.traffic[1].x,
		self.traffic[1].y,
		"SPEED:",
		self.traffic[1].speed
	)
	for i, traffic_car in ipairs(self.traffic) do

		Car.update(
			traffic_car,
			self.road.borders,
			{}
		)
		print(
		"TRAFFIC",
		i,
		"POSITION X Y:",
		traffic_car.x,
		traffic_car.y
		)
	
	end

	print(
	"TRAFFIC AFTER:",
	self.traffic[1].x,
	self.traffic[1].y,
	"SPEED:",
	self.traffic[1].speed
)

print(
"PLAYER X Y POSITION:",
self.player.x,
self.player.y
)
	Car.update(
		self.player,
		self.road.borders,
		self.traffic
	)

	print("=== PLAYER UPDATED ===")

	print(
	"PLAYER HAS SENSOR:",
	self.player.sensor ~= nil
)

print(
"PLAYER RAY COUNT:",
self.player.sensor and self.player.sensor.ray_count or -1
)

print(
"PLAYER READINGS:",
self.player.sensor and self.player.sensor.readings ~= nil
)	
print("=== SENSOR READINGS ===")

for i = 1, self.player.sensor.ray_count do

	local reading =
	self.player.sensor.readings[i]

	if reading then

		print(
		"PLAYER SENSOR",
		i,
		"DETECTED",
		"X:",
		reading.x,
		"Y:",
		reading.y,
		"OFFSET:",
		reading.offset
	)

else

	print(
	"PLAYER SENSOR",
	i,
	"NO DETECTION"
)

end
end

--========== end of test print out ===============================	
end
end




